### ISSUE TITLE
npm run setup fails on Windows

### ISSUE THREAD

**Issue by sgehrman** [irisli/stellarterm#107]
Just cloned the repo and did this:

$ npm run setup
npm ERR! stellar-terminal@0.0.1 setup: `npm install && ./node_modules/.bin/bower install`
npm ERR! Exit status 1

// entire output 

$ npm run setup

> stellar-terminal@0.0.1 setup f:\Github\stellarterm
> npm install && ./node_modules/.bin/bower install

> node-sass@4.5.3 install f:\Github\stellarterm\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\Steve\AppData\Roaming\npm-cache\node-sass\4.5.3\win32-x64-57_binding.node

> puppeteer@0.12.0 install f:\Github\stellarterm\node_modules\puppeteer
> node install.js

Downloading Chromium r508693 - 123.5 Mb [====================] 100% 0.0s
Chromium downloaded to f:\Github\stellarterm\node_modules\puppeteer\.local-chromium\win64-508693

> node-sass@4.5.3 postinstall f:\Github\stellarterm\node_modules\node-sass
> node scripts/build.js

Binary found at f:\Github\stellarterm\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1217 packages in 48.006s
'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stellar-terminal@0.0.1 setup: `npm install && ./node_modules/.bin/bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stellar-terminal@0.0.1 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Steve\AppData\Roaming\npm-cache\_logs\2017-11-26T03_13_10_436Z-debug.log

// error log

 $ cat ~/AppData/Roaming/npm-cache/_logs/2017-11-26T03_13_10_436Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'setup' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle stellar-terminal@0.0.1~presetup: stellar-terminal@0.0.1
6 info lifecycle stellar-terminal@0.0.1~setup: stellar-terminal@0.0.1
7 verbose lifecycle stellar-terminal@0.0.1~setup: unsafe-perm in lifecycle true
8 verbose lifecycle stellar-terminal@0.0.1~setup: PATH: c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;f:\Github\stellarterm\node_modules\.bin;c:\Users\Steve\bin;.;C:\Program Files (x86)\Git\local\bin;C:\Program Files (x86)\Git\mingw\bin;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\bin;c:\Program Files (x86)\Razer Chroma SDK\bin;c:\Program Files\Razer Chroma SDK\bin;c:\Program Files\ImageMagick-6.9.1-Q16;c:\ProgramData\Oracle\Java\javapath;c:\Windows\system32;c:\Windows;c:\Windows\System32\Wbem;c:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\Git\cmd;c:\Program Files\Microsoft SQL Server\120\Tools\Binn\;c:\Program Files (x86)\WinMerge;c:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;c:\WINDOWS\system32;c:\WINDOWS;c:\WINDOWS\System32\Wbem;c:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\GNU\GnuPG\pub;c:\Ruby22-x64\bin;c:\Ruby21-x64\bin;c:\NVPACK\jdk1.6.0_45\bin;c:\NVPACK\apache-ant-1.8.2\bin;c:\Program Files (x86)\GtkSharp\2.12\bin;c:\Program Files (x86)\Skype\Phone\;c:\Users\Steve\.dnx\bin;c:\Program Files\Microsoft DNX\Dnvm\;f:\Applications\php;c:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;c:\Program Files\Microsoft SQL Server\130\Tools\Binn\;c:\WINDOWS\system32;c:\WINDOWS;c:\WINDOWS\System32\Wbem;c:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files\Cloud Foundry;e:\GethWindows\;c:\Program Files\dotnet\;c:\Program Files\nodejs\;c:\Python27\;c:\Ruby22-x64\bin;c:\Ruby21-x64\bin;c:\NVPACK\android-sdk-windows\platform-tools;c:\NVPACK\android-sdk-windows\build-tools;c:\NVPACK\android-sdk-windows\tools;c:\NVPACK\jdk1.6.0_45\bin;c:\NVPACK\apache-ant-1.8.2\bin;c:\Users\Steve\AppData\Local\Microsoft\WindowsApps;c:\Users\Steve\AppData\Local\atom\bin;c:\Program Files\Heroku\bin;c:\Users\Steve\AppData\Local\GitHubDesktop\bin;c:\Users\Steve\AppData\Local\Microsoft\WindowsApps;c:\Users\Steve\AppData\Roaming\npm
9 verbose lifecycle stellar-terminal@0.0.1~setup: CWD: f:\Github\stellarterm
10 silly lifecycle stellar-terminal@0.0.1~setup: Args: [ '/d /s /c',
10 silly lifecycle   'npm install && ./node_modules/.bin/bower install' ]
11 silly lifecycle stellar-terminal@0.0.1~setup: Returned: code: 1  signal: null
12 info lifecycle stellar-terminal@0.0.1~setup: Failed to exec setup script
13 verbose stack Error: stellar-terminal@0.0.1 setup: `npm install && ./node_modules/.bin/bower install`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid stellar-terminal@0.0.1
15 verbose cwd f:\Github\stellarterm
16 verbose Windows_NT 10.0.16299
17 verbose argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "setup"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error stellar-terminal@0.0.1 setup: `npm install && ./node_modules/.bin/bower install`
22 error Exit status 1
23 error Failed at the stellar-terminal@0.0.1 setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by irisli** [comment]
Windows doesn't native support bash scripts. It'll work if you use some kind of bash on windows

**Comment by sgehrman** [comment]
I'm using bash on Windows. I use it for tons of node projects and always
works fine.

**Comment by irisli** [comment]
Ah thanks!

https://stackoverflow.com/questions/20765337/how-to-fix-is-not-an-internal-or-external-command-error

So i have to change `./node_modules/.bin/bower` to `node_modules/.bin/bower` and that should fix the problem. Can you try it out to see if it fixes the problem for you? Line 9 of package.json.

Thanks!

**Comment by sgehrman** [comment]
I did some searching on line and found that this is a popular issue for
Windows.

Someone online said that the ./node_modules/.bin was unnecessary, so I
removed it and it seems to work, but please confirm.

    "setup": "npm install && bower install",

That works.

-steve

**Comment by irisli** [comment]
The problem is that removing `./node_modules/.bin/` breaks the build on systems that don't have `./node_modules/.bin/` in the path. Additionally, bower could get resolved to some other globally installed bower. `./node_modules/.bin/` is the most portable for non-windows users.

**Comment by sgehrman** [comment]
Have you tested it? I thin I read that node searches node_modules/ but I'm
not sure. There's lots of info online about this. But I didn't see any good
answers.

**Comment by irisli** [comment]
Yeah, the part about the paths i'm sure about. node searches node_modules but the problem is actually with the shell.

When you run a command `bower`, the shell tries to look for what "bower" actually means. For properly configured systems with the `./node_modules/.bin/` added to the `PATH`, it should work.

However, I don't think most people have this properly configured.

**Comment by irisli** [comment]
One solution is to add it to the path automatically in each command. But thats also not the most beautiful
