### ISSUE TITLE
Error npm start

### ISSUE THREAD

**Issue by nash81** [irisli/stellarterm#992]
Error while trying to run npm start
on Ubuntu 18.04 and node v10.20.1

Error: Can't walk dependency graph: Cannot find module '../../images' from '/home/ubuntu/Downloads/stellarterm/src/components/NotFound'
    required by /home/ubuntu/Downloads/stellarterm/src/components/NotFound/NotFound.jsx
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
Error: Can't walk dependency graph: Cannot find module '../../images' from '/home/ubuntu/Downloads/stellarterm/src/components/ToastTemplate'
    required by /home/ubuntu/Downloads/stellarterm/src/components/ToastTemplate/ToastTemplate.jsx
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
Error: Can't walk dependency graph: Cannot find module '../../images' from '/home/ubuntu/Downloads/stellarterm/src/components/Download'
    required by /home/ubuntu/Downloads/stellarterm/src/components/Download/Download.jsx
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
Error: Can't walk dependency graph: Cannot find module '../../images' from '/home/ubuntu/Downloads/stellarterm/src/components/Markets'
    required by /home/ubuntu/Downloads/stellarterm/src/components/Markets/Markets.jsx
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
Error: Can't walk dependency graph: Cannot find module '../../images' from '/home/ubuntu/Downloads/stellarterm/src/components/Exchange'
    required by /home/ubuntu/Downloads/stellarterm/src/components/Exchange/Exchange.jsx
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
Error: Can't walk dependency graph: Cannot find module '../../images' from '/home/ubuntu/Downloads/stellarterm/src/components/HomePage'
    required by /home/ubuntu/Downloads/stellarterm/src/components/HomePage/HomePage.jsx
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
Error: Can't walk dependency graph: Cannot find module '../../images' from '/home/ubuntu/Downloads/stellarterm/src/components/Header'
    required by /home/ubuntu/Downloads/stellarterm/src/components/Header/Header.jsx
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
Error: Can't walk dependency graph: Cannot find module '../../images' from '/home/ubuntu/Downloads/stellarterm/src/components/Footer'
    required by /home/ubuntu/Downloads/stellarterm/src/components/Footer/Footer.jsx
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
Error: Can't walk dependency graph: Cannot find module '../../images' from '/home/ubuntu/Downloads/stellarterm/src/components/BuyCrypto'
    required by /home/ubuntu/Downloads/stellarterm/src/components/BuyCrypto/BuyCrypto.jsx
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/ubuntu/Downloads/stellarterm/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)

**Comment by jmysliv** [comment]
I have the same issue.
